name: Build
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  publish:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: ./scripts/build.sh

    - name: Run Test
      run: docker run ghcr.io/greenroom-robotics/nuclio_lighting_flash:latest
